theme: jekyll-theme-midnight

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# CORS in dev mode
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

baseurl: "/departmento"