theme: jekyll-theme-midnight

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# CORS in dev mode
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

url: "https://edward3h.github.io"
baseurl: "/departmento"